-- INSERT, UPDATE, and REMOVE data
INSERT INTO "AGENTS_PRIMARY" ("AGENT_CODE", "AGENT_NAME", "CITY")
VALUES ('A999', 'Bond', 'London'),
       ('A456', 'Kumar', 'Chennai');

SELECT *W
FROM "AGENTS_PRIMARY";

UPDATE "AGENTS_PRIMARY"
SET "AGENT_CODE" = 'A777'
WHERE "AGENT_NAME" = 'Bond';

SELECT *
FROM "AGENTS_PRIMARY";

DELETE FROM "AGENTS_PRIMARY"
WHERE "AGENT_CODE" = 'A008';

SELECT *
FROM "AGENTS_PRIMARY";

-- TRUNCATE TABLE "AGENTS_PRIMARY"; -- Deletes all the data in the table
-- DROP TABLE "AGENTS_PRIMARY"; -- Deletes the table itself


INSERT INTO "AGENTS_PRIMARY" ("AGENT_CODE", "AGENT_NAME", "CITY")
VALUES ('A777', 'Bond', 'London')
    ON CONFLICT ("AGENT_CODE")
DO NOTHING;


INSERT INTO "AGENTS_PRIMARY" ("AGENT_CODE", "AGENT_NAME", "CITY")
VALUES ('A777', 'Bond', 'London')
    ON CONFLICT ("AGENT_CODE")
DO UPDATE SET "CITY" = 'Bermuda';

SELECT *
FROM "AGENTS_PRIMARY";

INSERT INTO "AGENTS_PRIMARY" ("AGENT_CODE", "AGENT_NAME", "CITY")
VALUES ('A011', 'Abraham', 'London')
    ON CONFLICT ("AGENT_CODE")
DO UPDATE SET "AGENT_NAME" = 'Abraham', "CITY" = 'London';

INSERT INTO "AGENTS_PRIMARY" ("AGENT_CODE", "AGENT_NAME", "CITY")
VALUES ('A011', 'Abraham', 'London')
    ON CONFLICT ("AGENT_CODE")
DO UPDATE SET "AGENT_NAME" = "EXCLUDED"."AGENT_NAME";